plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.version
group = project.group

repositories {
    maven {
        name = "meteor-maven"
        url = "https://maven.meteordev.org/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    compileOnly 'org.projectlombok:lombok:1.18.48'
    annotationProcessor 'org.projectlombok:lombok:1.18.48'

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation("meteordevelopment:orbit:${project.orbit_version}")
    include("meteordevelopment:orbit:${project.orbit_version}")
    implementation("io.github.racoondog:norbit:${project.norbit_version}")
    include("io.github.racoondog:norbit:${project.norbit_version}")
    implementation 'net.java.dev.jna:jna:5.17.0'

    // NanoVG (LWJGL)
    implementation(platform("org.lwjgl:lwjgl-bom:3.3.6"))
    implementation("org.lwjgl:lwjgl-nanovg")
    runtimeOnly("org.lwjgl:lwjgl-nanovg::natives-windows")
    runtimeOnly("org.lwjgl:lwjgl-nanovg::natives-macos")
    runtimeOnly("org.lwjgl:lwjgl-nanovg::natives-macos-arm64")
    runtimeOnly("org.lwjgl:lwjgl-nanovg::natives-linux")
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_$projectName"}
    }
    manifest {
        attributes 'Premain-Class': 'cc.silk.utils.jvm.Agent'
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}
