# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.0.0
group=com.silk
archives_base_name=silk-id

# Dependencies
fabric_api_version=0.155.3+26.1.2
fabric_version=0.155.3+26.1.2

# Event Libraries
orbit_version=0.2.4
norbit_version=1.2.0
